# -*- coding: utf-8 -*-
"""Group_4_capstone project_ACE batch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cajSpWsjEsTrcKXW5AcDlVdMPa4utMJQ
"""

from google.colab import files
uploaded = files.upload()

from IPython.display import display
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Diabetes_data.csv")
print("Shape :",df.shape)
# print("\nfirst 5 rows :", df.head())
pd.set_option('display.max_columns', None)
display(df.head())

print(df.info())

df.describe()

print("missing values :\n",df.isnull().sum())

df.duplicated().count()

"""Duplicate records were identified. Since the dataset represents survey respondents and does not contain a unique patient identifier, identical records may correspond to different individuals. Therefore, duplicates were retained."""

labels= {0.0 :"No Diabetes",1.0:"Pre Diabetic",2.0:"Diabetic"}
print("\nTarget variable distribution:")
print(df["Diabetes_012"].map(labels).value_counts())

Diabetes_percent = df.groupby("Diabetes_012")["Diabetes_012"].count()/len(df)*100
plt.figure(figsize=(5,5,))
plt.pie( Diabetes_percent, autopct="%1.1f%%", labels= ["No Diabetees","Pre-Diabetic","Diabetic"])
plt.tight_layout()
plt.show()
print(Diabetes_percent)

plt.figure(figsize=(4,4))
ax = sns.countplot(x='Diabetes_012', data=df, hue='Diabetes_012', palette='Set2', legend=False)
plt.title('Patient Distribution by Diabetes Status')
plt.xticks([0,1,2], ['No Diabetes', 'Pre-Diabetic', 'Diabetic'])
plt.ylabel('Count')
for p in ax.patches:
    ax.annotate(f'{int(p.get_height()):,}',
                (p.get_x() + p.get_width()/2, p.get_height()+500),
                ha='center', fontsize=8)
plt.tight_layout()
plt.savefig('plot1_target.png', dpi=150)
plt.show()

plt.figure(figsize=(8,6))
sns.boxplot(data=df,x="Diabetes_012",y="BMI", palette='Set1')
plt.title("BMI distribution by Diabetes status")
plt.xticks([0,1,2],["No Diabetes","Pre Diabetic","Diabetic"])
plt.ylabel("BMI")
plt.savefig("BMI_plot.png",dpi= 200)

age_labels = {1:'18-24', 2:'25-29', 3:'30-34', 4:'35-39', 5:'40-44',
              6:'45-49', 7:'50-54', 8:'55-59', 9:'60-64', 10:'65-69',
              11:'70-74', 12:'75-79', 13:'80+'}

age_diabetes = df[df['Diabetes_012']==2.0].groupby('Age').size()

plt.figure(figsize=(10,5))
age_diabetes.plot(kind='bar', color='tomato')
plt.title('Diabetic Patients by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Number of Diabetic Patients')
plt.xticks(range(13), list(age_labels.values()), rotation=45)
plt.tight_layout()
plt.savefig('plot3_age.png', dpi=150)
plt.show()

bmi_means = df.groupby("Diabetes_012")["BMI"].mean().round(2)
print("Average BMI by Diabetes Status:")
print(f"  No Diabetes:  {bmi_means[0.0]}")
print(f"  Pre-Diabetic: {bmi_means[1.0]}")
print(f"  Diabetic:     {bmi_means[2.0]}")
print(f"\n📌 Difference: {(bmi_means[2.0] - bmi_means[0.0]):.1f} BMI points higher in diabetics")
print("📌 Clinical obesity threshold is BMI = 30")

df.groupby("Diabetes_012")["BMI"].mean().round(1)

# Create BMI slabs
df["BMI_Category"] = pd.cut(
    df["BMI"],
    bins=[0, 18.5, 25, 30, 100],
    labels=["Underweight", "Normal", "Overweight", "Obese"]
)

# Count BMI categories by diabetes status
bmi_slab = df.groupby("Diabetes_012")["BMI_Category"].value_counts()

print("BMI Slabs by Diabetes Status")
print(bmi_slab)

df["BMI_Category1"]= pd.cut(df["BMI"],bins =[0,18.5,25,30,100], labels= ["Underweight","Normal","Overweight","Obese"])
BMI_slab = df.groupby("BMI_Category1")["Diabetes_012"].value_counts(normalize= True)*100
BMI_slab

BMI_slab = (
    df.groupby("BMI_Category1")["Diabetes_012"]
    .value_counts(normalize=True)
    .mul(100)
    .unstack()
)

BMI_slab.plot(
    kind="bar",
    stacked=True,
    figsize=(10,6)
)

plt.ylabel("Percentage")
plt.title("Diabetes Distribution Across BMI Categories")

plt.show()

BMI_slab = (df.groupby("BMI_Category1")["Diabetes_012"].value_counts(normalize= True).mul(100).unstack())

diabetic_df = df[df['Diabetes_012'] == 2.0]
age_55_plus = diabetic_df[diabetic_df['Age'] >= 8]  # Age 8 = 55-59 years
pct = len(age_55_plus) / len(diabetic_df) * 100
print(f"📌 {pct:.1f}% of all diabetic patients are aged 55 or above")

df["Age_Category"] = df["Age"].replace({
    1: "18-24",
    2: "25-29",
    3: "30-34",
    4: "35-39",
    5: "40-44",
    6: "45-49",
    7: "50-54",
    8: "55-59",
    9: "60-64",
    10: "65-69",
    11: "70-74",
    12: "75-79",
    13: "80+"
})

import pandas as pd
import matplotlib.pyplot as plt

# Create BMI categories
df["BMI_Category"] = pd.cut(
    df["BMI"],
    bins=[0, 18.5, 25, 30, 35, 100],
    labels=["Underweight", "Normal", "Overweight", "Obese", "Severely Obese"]
)

# Calculate diabetes percentage
diabetes_percent = (
    df.groupby("BMI_Category")["Diabetes_012"]
    .mean() * 100
)

# Plot
plt.figure(figsize=(6,5))

plt.bar(diabetes_percent.index.astype(str),
        diabetes_percent.values)

# Data labels
for i, value in enumerate(diabetes_percent.values):
    plt.text(i, value + 1, f"{value:.1f}%")

plt.xlabel("BMI Category")
plt.ylabel("Diabetes Percentage")
plt.title("Diabetes % by BMI Category")

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

diabetic_df = df[df["Diabetes_012"] == 2.0]

Diabetes_percent = (
    diabetic_df["Age_Category"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

plt.figure(figsize=(6,3))

sns.barplot(
    x=Diabetes_percent.index,
    y=Diabetes_percent.values,
    palette="Set1"
)

plt.xlabel("Age Category")
plt.ylabel("Diabetes Percentage")

plt.title("Age Distribution Among Diabetic Patients")

plt.xticks(rotation=45)

plt.show()

overall_rate = (df['Diabetes_012'] == 2.0).mean() * 100

triple_threat = df[(df['HighBP']==1) &
                   (df['HighChol']==1) &
                   (df['PhysActivity']==0)]

triple_rate = (triple_threat['Diabetes_012'] == 2.0).mean() * 100
multiplier = triple_rate / overall_rate

print(f"Overall diabetes rate in dataset:     {overall_rate:.1f}%")
print(f"Diabetes rate in Triple Threat group: {triple_rate:.1f}%")
print(f"📌 Triple threat patients are {multiplier:.1f}x MORE likely to be diabetic")

# Visualize
labels = ['Overall Population', 'High BP + High Chol\n+ No Exercise']
values = [overall_rate, triple_rate]
colors = ['steelblue', 'crimson']

plt.figure(figsize=(7,5))
bars = plt.bar(labels, values, color=colors, width=0.4)
plt.title('Diabetes Rate: General vs Triple Risk Group', fontsize=13)
plt.ylabel('Diabetes Prevalence (%)')
for bar, val in zip(bars, values):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height()+0.3,
             f'{val:.1f}%', ha='center', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('insight3_triple_threat.png', dpi=150)
plt.show()

high_bmi = df[df['BMI'] > 30]

active = high_bmi[high_bmi['PhysActivity']==1]
inactive = high_bmi[high_bmi['PhysActivity']==0]

active_rate = (active['Diabetes_012']==2.0).mean() * 100
inactive_rate = (inactive['Diabetes_012']==2.0).mean() * 100

print(f"Among HIGH BMI patients (BMI > 30):")
print(f"  Physically Active   → Diabetes Rate: {active_rate:.1f}%")
print(f"  Physically Inactive → Diabetes Rate: {inactive_rate:.1f}%")
print(f"📌 Inactive high-BMI patients are {inactive_rate/active_rate:.1f}x more at risk")

active = df[df['PhysActivity'] == 1]

"""## **Outlier Demonstration**
Since most variables are categorical we will focus on -: BMI, Physical Health and Mental Health

"""

# Boxplots
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.boxplot(x=df['BMI'], ax=axes[0])
axes[0].set_title('BMI')

sns.boxplot(x=df['MentHlth'], ax=axes[1])
axes[1].set_title('Mental Health Days')

sns.boxplot(x=df['PhysHlth'], ax=axes[2])
axes[2].set_title('Physical Health Days')

plt.tight_layout()
plt.show()

# Outliers calculation Using IQR

def find_outliers_iqr(data, column):

    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower_bound) |
        (data[column] > upper_bound)
    ]

    print(f"{column}")
    print(f"Lower Bound: {lower_bound}")
    print(f"Upper Bound: {upper_bound}")
    print(f"Outliers Found: {len(outliers)}")
    print(" ")

    return outliers

bmi_outliers = find_outliers_iqr(df, 'BMI')
mental_outliers = find_outliers_iqr(df, 'MentHlth')
physical_outliers = find_outliers_iqr(df, 'PhysHlth')

# Percentage of Outliers

bmi_pct = len(bmi_outliers)/len(df)*100
print(f"BMI Outliers: {bmi_pct:.2f}%")

mental_pct = len(mental_outliers)/len(df)*100
print(f"Mental Health Outliers: {mental_pct:.2f}%")

physical_pct = len(physical_outliers)/len(df)*100
print(f"Physical Health Outliers: {physical_pct:.2f}%")

# Histograms for distributions

fig, axes = plt.subplots(1,3, figsize=(15,4))

sns.histplot(df['BMI'], bins=30, ax=axes[0])
axes[0].set_title('BMI Distribution')

sns.histplot(df['MentHlth'], bins=30, ax=axes[1])
axes[1].set_title('Mental Health Days')

sns.histplot(df['PhysHlth'], bins=30, ax=axes[2])
axes[2].set_title('Physical Health Days')

plt.tight_layout()
plt.show()

"""Outlier detection was performed on BMI, MentHlth, and PhysHlth using boxplots and the IQR method. BMI showed 6,424 outliers (3.92%), while MentHlth and PhysHlth showed 23,071 (14.09%) and 26,046 (15.90%) outliers respectively. These observations correspond to individuals with extreme but plausible health conditions, such as severe obesity or prolonged periods of poor mental and physical health. Since the values are clinically meaningful and not indicative of data-entry errors, all outliers were retained for subsequent analysis.

## **Hypothesis testing**

Test 1: BMI differs among diabetes groups (ANOVA)

Hypotheses

H₀: Mean BMI is the same across all diabetes groups.

H₁: At least one diabetes group has a different mean BMI
"""

from scipy.stats import f_oneway

group0 = df[df['Diabetes_012']==0]['BMI']
group1 = df[df['Diabetes_012']==1]['BMI']
group2 = df[df['Diabetes_012']==2]['BMI']

f_stat, p_value = f_oneway(group0, group1, group2)

print("F-statistic:", f_stat)
print("P-value:", p_value)
print('Since p-value < 0.05, we reject H₀')

labels = {0.0 :"No Diabetes",1.0:"Pre Diabetic",2.0:"Diabetic"}


# Mean BMI of each target value group
mean_bmi_by_diabetes = df.groupby('Diabetes_012')['BMI'].mean()
print("\nMean BMI by Diabetes Group:")
print(mean_bmi_by_diabetes.rename(index=labels))

"""Test 2: Age differs among diabetes groups (Chi-Square Test, as in our dataset Age is really an ordered category encoded as numbers)

Hypotheses

H₀: Mean age category is the same across diabetes groups.

H₁: Mean age category differs among diabetes groups.
"""

from scipy.stats import chi2_contingency

table = pd.crosstab(df['Age'], df['Diabetes_012'])

chi2, p, dof, expected = chi2_contingency(table)

print("Chi-square:", chi2)
print("P-value:", p)
print('Since p-value < 0.05, we reject H₀')

age_diabetes = pd.crosstab(df['Age'], df['Diabetes_012'])
age_diabetes.rename(columns={ 0.0: 'No Diabetes', 1.0: 'Pre-Diabetic', 2.0: 'Diabetic'}, inplace=True)
age_labels = { 1:'18-24', 2:'25-29', 3:'30-34', 4:'35-39', 5:'40-44', 6:'45-49', 7:'50-54', 8:'55-59', 9:'60-64', 10:'65-69', 11:'70-74', 12:'75-79', 13:'80+'}

age_diabetes.index = age_diabetes.index.map(age_labels)
age_diabetes.plot(kind='bar', figsize=(10,5))

plt.title("Age Category vs Diabetes Status")
plt.xlabel("Age Category")
plt.ylabel("Count")
plt.show()

"""Test 3: HighBP associated with diabetes (Chi-Square Test)


Hypotheses

H₀ : High Blood Pressure and Diabetes Status are independent.

H₁ : High Blood Pressure and Diabetes Status are associated.

"""

print(pd.crosstab(df['HighBP'], df['Diabetes_012']))
print('')

from scipy.stats import chi2_contingency

table = pd.crosstab(df['HighBP'], df['Diabetes_012'])

chi2, p, dof, expected = chi2_contingency(table)

print("Chi-square:", chi2)
print("P-value:", p)
print("The test produced a p-value less than 0.05, leading to the rejection of the null hypothesis.")

bp_diabetes = pd.crosstab(df['HighBP'], df['Diabetes_012'])

bp_diabetes.rename(
    index={0:'No High BP',1:'High BP'},
    columns={0:'No Diabetes',1:'Pre-Diabetic',2:'Diabetic'},
    inplace=True
)

bp_diabetes.plot(kind='bar', figsize=(8,5))

plt.title('High Blood Pressure vs Diabetes Status')
plt.xlabel('Blood Pressure Status')
plt.ylabel('Count')
plt.show()

"""Below is Chi-Square test for Veggies

Though p-value is <.05, it is to be noted chi-square is significatly lower compared to High BP and Age, indicating lower association)

"""

table = pd.crosstab(df['Veggies'], df['Diabetes_012'])

chi2, p, dof, expected = chi2_contingency(table)

print("Chi-square:", chi2)
print("P-value:", p)

"""## **Correlation Vs Causation Discussions**"""

plt.figure(figsize=(14,10))
# Drop non-numeric columns before calculating correlation
numeric_df = df.drop(columns=['BMI_Category', 'BMI_Category1', 'Age_Category'], errors='ignore')
corr = numeric_df.corr()
mask = np.triu(np.ones_like(corr, dtype=bool))  # show only lower triangle
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f',
            cmap='BrBG', linewidths=0.5, annot_kws={"size":7})
plt.title('Correlation Heatmap — All Features', fontsize=14)
plt.tight_layout()
plt.savefig('plot5_heatmap.png', dpi=150)
plt.show()


corr_target = corr['Diabetes_012'].sort_values()

plt.figure(figsize=(8,6))
corr_target.drop('Diabetes_012').plot(kind='barh')
plt.title('Correlation of Features with Diabetes')
plt.xlabel('Correlation Coefficient')
plt.show()

"""Obresvtaions-:

A. Positive Correlations
1. General Health (0.30) -: This is the strongest correlation observed with the target variable.
2. High Blood Pressure (0.27) -: Individuals with hypertension are more likely to be diabetic. This supports existing medical evidence.
3. BMI (0.22) -: Obesity appears to be an important risk factor.



B. Negative Correlations
1. Income (-0.17) -: Higher income levels are associated with lower diabetes prevalence.
2. Education (-0.13) -:Individuals with higher education levels tend to show lower diabetes prevalence.
3. Physical Activity (-0.12) -: Regular physical activity is associated with reduced diabetes prevalence.


Although several variables show meaningful correlations with diabetes, correlation does not imply causation. For example:

* BMI is positively correlated with diabetes, but this does not prove that increased BMI alone causes diabetes.
* Physical activity is negatively correlated with diabetes, but other factors such as diet, age, and socioeconomic status may also influence this relationship.
* High blood pressure and diabetes may occur together because they share common risk factors rather than one directly causing the other.

Therefore, the correlations identified in this analysis should be interpreted as associations rather than definitive causal relationships.

# **PATIENT SEGMENTATION USING K-MEANS CLUSTERING**
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

df = pd.read_csv(
    "diabetes_012_health_indicators_BRFSS2015.csv"
)

cluster_features = [

    'BMI',

    'Age',

    'PhysHlth',

    'HighBP',

    'HighChol',

    'DiffWalk',

    'HeartDiseaseorAttack',

    'GenHlth'

]

X = df[cluster_features]

print(X.shape)
X.head()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled.shape)

pd.DataFrame(
    X_scaled,
    columns=cluster_features
).describe()

from sklearn.cluster import KMeans

wcss = []

for k in range(2,7):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X_scaled)

    wcss.append(
        kmeans.inertia_
    )

print(wcss)

plt.figure(figsize=(8,5))

plt.plot(
    range(2,7),
    wcss,
    marker='o'
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("WCSS")
plt.title("Elbow Method")

plt.grid(True)

plt.show()

# FINAL K-MEANS MODEL

kmeans = KMeans(

    n_clusters=4,

    random_state=42,

    n_init=10

)

df['Cluster'] = kmeans.fit_predict(
    X_scaled
)

# NUMBER OF PATIENTS IN EACH CLUSTER

df['Cluster'].value_counts()

cluster_names = {

    0 : "Healthy Profile",

    1 : "High Risk Group",

    2 : "Moderate-High Risk Group",

    3 : "Moderate Risk Group"

}

df['Cluster_Name'] = (

    df['Cluster']

    .map(cluster_names)

)

plt.figure(figsize=(10,5))

sns.countplot(

    x='Cluster_Name',

    data=df

)

plt.title(
    "Patient Distribution Across Clusters"
)

plt.show()

cluster_profile = (

    df.groupby('Cluster_Name')[

        cluster_features

    ]

    .mean()

)

display(
    cluster_profile
)

cluster_diabetes = pd.crosstab(

    df['Cluster_Name'],

    df['Diabetes_012'],

    normalize='index'

) * 100

display(
    cluster_diabetes
)

cluster_diabetes.plot(

    kind='bar',

    figsize=(8,5)

)

plt.title(
    "Diabetes Percentage by Cluster"
)

plt.ylabel("Percentage")

plt.show()

df['Cluster_Name'].value_counts()

"""## **SQL Queries**"""



"""Dashboard"""



"""Gen AI Integration"""

